### ISSUE TITLE
Adding minifying package into the project.

### ISSUE THREAD

**Issue by liitlelenim** [fire-ui/fire-ui#21]
It could make it easier for users and developers to create a minified version of changes they made to customize styling.

**Comment by kimlimjustin** [comment]
I don't really get what you mean, however, if you mean to minify FireUI.css and FireUI.js, there are already minified files (although I minify it manually). If you mean to use Github actions to auto minify files, we've tried it but it didn't work 😅. Or do you mean to include a dependency package to minify files?

**Comment by liitlelenim** [comment]
I mean using dependency package, sorry for a poor description of this issue 😅.

**Comment by kimlimjustin** [comment]
Oh sure, but please remember to update the contributing guidelines too to make sure users minify files before submitting PR.
