### ISSUE TITLE
Data theme switch and other themes expect dark and light don't work

### ISSUE THREAD

**Issue by IronManCool001** [fire-ui/fire-ui#45]
**Describe the bug**
Data theme switch and other themes expect dark and light don't work

**To Reproduce**
1.  Copy the code from [docs](https://fire-ui.netlify.app/docs/colors)

**Expected behavior**
Themes like aqua and phoenix should work as well as the buttons should change the theme

**Smartphone (please complete the following information):**
 - Device: Asus zenfone max pro m1
 - OS: Android 9
 - Browser => Chrome

**Comment by kimlimjustin** [comment]
Ohh, thanks for report it! It's because I forgot to update the code on the [docs](https://github.com/fire-ui/fire-ui.github.io/blob/next-docs/src/posts/colors.md) . I'll fix it as soon as possible

**Comment by kimlimjustin** [comment]
https://github.com/fire-ui/fire-ui.github.io/tree/25c2570c8d41174ee7fa8886191bd63be7fef31b
